CREATE TABLE IF NOT EXISTS posts (
id INTEGER PRIMARY KEY AUTOINCREMENT,
date_time VARCHAR NOT NULL,
posting_title VARCHAR NOT NULL,
listing_price INTEGER NOT NULL,
location VARCHAR NOT NULL,
url VARCHAR NOT NULL,
term VARCHAR NOT NULL,
UNIQUE (url)
);

CREATE TABLE IF NOT EXISTS searches (
id INTEGER PRIMARY KEY AUTOINCREMENT,
term VARCHAR NOT NULL,
time VARCHAR NOT NULL,
url VARCHAR NOT NULL
);